name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: install
        run: yarn

      - name: build
        run: yarn build

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v1.2.0
        with:
          github-token: ${{ secrets.github_token }}

      - name: publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
